# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-08-11 16:51:20
For one travel speed scenario (raster), for one type of points of interests, calculate the journey duration from each village to the nearest point of interest.
"""
import arcpy
from arcpy.sa import *

def Access_calculation():

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("ImageExt")

    arcpy.ImportToolbox(r"Conversion Tools.tbx")
    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"Default.gdb", workspace=r"Default.gdb"):
        points_of_interest = "Hospitals" #HighSchools, Markets (Points)
        travel_speeds = "travel_speeds" #Change according to scenarios (Raster)
        cambodian_village = "cambodian_village" # Points

        # Process: Cost Distance (Cost Distance) (sa)
        TTtoPOI = "tttohs"
        Cost_Distance = TTtoPOI
        Output_backlink_raster = ""
        TTtoPOI = arcpy.sa.CostDistance(in_source_data=points_of_interest, in_cost_raster=travel_speeds, maximum_distance=None, out_backlink_raster=Output_backlink_raster, source_cost_multiplier="", source_start_cost="", source_resistance_rate="", source_capacity="", source_direction="")
        TTtoPOI.save(Cost_Distance)


        # Process: Raster Calculator (Raster Calculator) (sa)
        tttoPOI_min = "tt_poi_min"
        Raster_Calculator = tttoPOI_min
        tttoPOI_min = TTtoPOI/0.05478
        tttoPOI_min.save(Raster_Calculator)


        # Process: Zonal Statistics as Table (Zonal Statistics as Table) (sa)
        Results_Table_Name = "tt_vil_min"
        arcpy.sa.ZonalStatisticsAsTable(in_zone_data=cambodian_village, zone_field="village_co", in_value_raster=tttoPOI_min, out_table=Results_Table_Name, ignore_nodata="DATA", statistics_type="MINIMUM", process_as_multidimensional="CURRENT_SLICE", percentile_values=90, percentile_interpolation_type="AUTO_DETECT")
        .save(Zonal_Statistics_as_Table)


        # Process: Table To Excel (Table To Excel) (conversion)
        tt_vil_min_name_xlsx = "tt_vil_min_%points_of_interest%_%travel_speeds%.xlsx"
        arcpy.conversion.TableToExcel(Input_Table=Results_Table_Name, Output_Excel_File=tt_vil_min_name_xlsx, Use_field_alias_as_column_header="NAME", Use_domain_and_subtype_description="CODE")

if __name__ == '__main__':
    Access_calculation()
